package com.Manipulus.arctic.job.model;

import jakarta.persistence.*;
import java.io.Serializable;
import java.util.Date;
import com.Manipulus.arctic.customer.model.Customer;

@Entity
@Table(name = "job")
public class Job implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false, updatable = false)
    private long id; // The ID of the job, autogenerated by the database.

    @ManyToOne
    @JoinColumn(name = "customer_id")
    private Customer customer; // The customer associated with the job.

    @Column(name = "job_type")
    private String job_type; // The type of the job.

    @Column(name = "job_date")
    private Date job_date; // The date when the job was created.

    @Column(name = "job_status")
    private String job_status; // The status of the job.

    @Column(name = "location")
    private String location;

    @Column(nullable = false, updatable = false)
    private String jobCode; // A unique code assigned to the job.

    public String getJobCode() {
        return jobCode;
    }

    public void setJobCode(String customerCode) {
        this.jobCode = customerCode;
    }
    // Default constructor for the Job class.
    public Job() {

    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public String getJob_type() {
        return job_type;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public void setJob_type(String job_type) {
        this.job_type = job_type;
    }

    public Date getJob_date() {
        return job_date;
    }

    public void setJob_date(Date job_date) {
        this.job_date = job_date;
    }

    public String getJob_status() {
        return job_status;
    }

    public void setJob_status(String job_status) {
        this.job_status = job_status;
    }
    // Constructor for the Job class that takes in all the attributes.
    public Job(Customer customer, String job_type, Date job_date, String job_status, String jobCode , String location) {
        this.customer = customer;
        this.job_type = job_type;
        this.job_date = job_date;
        this.job_status = job_status;
        this.jobCode = jobCode;
        this.location=location;
    }
    // Overrides the toString() method to return a string representation of the Job object.
    @Override
    public String toString() {
        return "Job{" +
                "id=" + id +
                ", customer=" + customer +
                ", job_type=" + job_type +
                ", job_date=" + job_date +
                ", job_status=" + job_status +
                ", location=" + location +
                '}';
    }
}