package com.Manipulus.arctic.location.model;

import jakarta.persistence.*;
import java.io.Serializable;
import java.util.Date;
import com.Manipulus.arctic.customer.model.Customer;

@Entity
@Table(name = "location")
public class location implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false, updatable = false)
    private long id; // The ID of the location, autogenerated by the database.

    @Column(name = "location_lat")
    private String location_lat; // The type of the location.

    @Column(name = "location_lng")
    private String location_lng; // The date when the location was created.

    @Column(name = "location_title")
    private String location_title; // The status of the location.

    @Column(name = "location_info")
    private String location_info;

    @Column(nullable = false, updatable = false)
    private String locationCode; // A unique code assigned to the location.

    public String getlocationCode() {
        return locationCode;
    }

    public void setlocationCode(String customerCode) {
        this.locationCode = customerCode;
    }
    // Default constructor for the location class.
    public location() {
    }

    public location(long id, String location_lat, String location_lng, String location_title, String location_info, String locationCode) {
        this.id = id;
        this.location_lat = location_lat;
        this.location_lng = location_lng;
        this.location_title = location_title;
        this.location_info = location_info;
        this.locationCode = locationCode;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getLocation_lat() {
        return location_lat;
    }

    public void setLocation_lat(String location_lat) {
        this.location_lat = location_lat;
    }

    public String getLocation_lng() {
        return location_lng;
    }

    public void setLocation_lng(String location_lng) {
        this.location_lng = location_lng;
    }

    public String getLocation_title() {
        return location_title;
    }

    public void setLocation_title(String location_title) {
        this.location_title = location_title;
    }

    public String getLocation_info() {
        return location_info;
    }

    public void setLocation_info(String location_info) {
        this.location_info = location_info;
    }

    @Override
    public String toString() {
        return "location{" +
                "id=" + id +
                ", location_lat='" + location_lat + '\'' +
                ", location_lng=" + location_lng +
                ", location_title='" + location_title + '\'' +
                ", location_info='" + location_info + '\'' +
                ", locationCode='" + locationCode + '\'' +
                '}';
    }
}